// Isolated PostgreSQL contract test. No ENV or external services.
import { readFile, readdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const { PGlite } = await import(pathToFileURL(process.argv[2]).href);
const db = new PGlite();
let checks=0;
const check=(v)=>{assert.ok(v);checks++};
const query=async(s,p=[])=> (await db.query(s,p)).rows;
const scalar=async(s,p=[])=>Object.values((await query(s,p))[0])[0];
const rejects=async(fn)=>{let failed=false;try{await fn()}catch{failed=true}check(failed)};
try {
 await db.exec('create role anon;create role authenticated;create role service_role bypassrls;grant usage on schema public to service_role;');
 await db.exec('create schema storage;create table storage.buckets(id text primary key,name text not null,public boolean not null default false);');
 await db.exec(await readFile('sql/001_initial_schema.sql','utf8'));
 for(const file of (await readdir('supabase/migrations')).sort().filter(f=>!f.endsWith('_initial.sql')))
  await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
 check(await scalar('select version from public.bookpromo_schema')===4);
 await db.exec('set role service_role');
 const ids=Array.from({length:4},()=>crypto.randomUUID());
 const [book,version,chapter,quote]=ids;
 const text='Der Motor läuft ruhig durch die dunkle Nacht.';
 const payload={hash:'initial',book:{id:book,title:'Testbuch',promotion_enabled:true},version:{id:version,filename:'test.docx',file_sha256:'a'.repeat(64),extraction_revision:1,analysis_version:'test'},
 chapters:[{id:chapter,position:1,name:'Kapitel',source_text:text,paragraphs:[]}],
 quotes:[{id:quote,chapter_id:chapter,text,source_start:0,source_end:text.length,scores:{clarity:5},reason:'Test',spoiler:'none',approved:true,blocked:false}]};
 const sync=async(p,rev)=>scalar('select public.bookpromo_sync($1::jsonb,$2)',[JSON.stringify(p),rev]);
 check((await sync(payload,0)).revision===1);
 check((await sync(payload,0)).revision===1);
 await rejects(()=>sync({...payload,hash:'other'},0));
 await rejects(()=>sync({...payload,hash:'null-revision'},null));
 await rejects(()=>sync({...payload,hash:'bad',quotes:[{...payload.quotes[0],text:'Invented'}]},1));
 check(await scalar('select count(*) from public.quotes')===1);
 await db.query("insert into public.promotion_settings(account_id,active,telegram_chat_id,telegram_user_id) values ('test',true,'42','7')");
 const reserve=async()=>scalar("select public.bookpromo_reserve('test',date '2026-09-08')");
 let r=await reserve();check(r.outcome==='created');let d=r.post;
 check(d.book_profile.chapter_position===1 && d.book_profile.chapter_name==='Kapitel');
 check((await scalar('select public.bookpromo_transition($1,null,null,$2)',[d.id,'fail'])).outcome==='stale');
 check((await reserve()).outcome==='existing');
 await rejects(()=>sync({...payload,hash:'open'},1));
 const move=async(action,data={},post=d)=>scalar('select public.bookpromo_transition($1,$2,$3,$4,$5::jsonb)',[post.id,post.revision,post.action_token,action,JSON.stringify(data)]);
 check((await move('image_ready',{image_url:'https://example.org/x.jpg'})).outcome==='invalid_state');
 check((await move('approve_image',{chat_id:'42',user_id:'7'})).outcome==='invalid_state');
 await rejects(()=>move('text_ready',{caption:'Invented',image_prompt:'Test'}));
 d=(await move('text_ready',{caption:text+'\nEin Roman.',image_prompt:'Nacht'})).post;
 await rejects(()=>move('approve_text',{chat_id:'42',user_id:'wrong'}));
 await rejects(()=>move('approve_text',{}));
 let old=d;d=(await move('approve_text',{chat_id:'42',user_id:'7'})).post;
 check(d.status==='generating_image' && d.text_approved_at);
 check((await move('approve_text',{chat_id:'42',user_id:'7'},old)).outcome==='stale');
 d=(await move('image_ready',{image_url:'https://example.org/x.jpg'})).post;
 const caption=d.caption;
 d=(await move('retry_image',{chat_id:'42',user_id:'7'})).post;
 check(d.status==='generating_image' && d.caption===caption);
 d=(await move('image_ready',{image_url:'https://example.org/new.jpg'})).post;
 d=(await move('retry_text',{chat_id:'42',user_id:'7'})).post;
 check(d.status==='generating_text' && d.caption===null && d.text_approved_at===null && d.image_path===null);
 d=(await move('text_ready',{caption:text,image_prompt:'Nacht'})).post;
 d=(await move('approve_text',{chat_id:'42',user_id:'7'})).post;
 d=(await move('image_ready',{image_url:'https://example.org/final.jpg'})).post;
 d=(await move('approve_image',{chat_id:'42',user_id:'7'})).post;
 check(d.status==='approved' && d.approved_revision===d.revision);
 check(await scalar('select last_published_at is null from public.quote_overview where id=$1',[quote]));
 d=(await move('begin_publish')).post;
 d=(await move('container_ready',{container_id:'container'})).post;
 d=(await move('publish_uncertain')).post;
 check((await reserve()).outcome==='existing');
 d=(await move('published',{media_id:'media'})).post;
 check(d.status==='published');
 check(await scalar('select not reserved and last_published_at is not null from public.quote_overview where id=$1',[quote]));
 const quote2=crypto.randomUUID();
 await db.query("insert into public.quotes(id,chapter_id,text,source_start,source_end,scores,selection_reason,spoiler_level,approved,blocked,current) values ($1,$2,'Motor',4,9,'{}','Test','none',true,false,true)",[quote2,chapter]);
 let sameDay=await scalar("select public.bookpromo_reserve('test',date '2026-09-08')");
 check(sameDay.outcome==='created' && sameDay.post.quote_id===quote2);
 sameDay=(await move('fail',{},sameDay.post)).post;
 check(sameDay.status==='failed');
 await db.query('update public.quotes set blocked=true where id=$1',[quote2]);
 await rejects(()=>sync({...payload,hash:'changed-source',version:{...payload.version,extraction_revision:2}},1));
 const updated={...payload,hash:'settings',book:{...payload.book,title:'Updated'}};
 check((await sync(updated,1)).revision===2);
 check((await scalar("select public.bookpromo_reserve('test',date '2026-09-09')")).outcome==='no_quote');
 await db.exec('reset role;set role anon');
 await rejects(()=>sync(payload,2));
 await rejects(()=>reserve());
 await rejects(()=>query('select * from public.books'));
 console.log(`Integration v4: ${checks} PostgreSQL-Prüfungen erfolgreich.`);
} finally {await db.close()}
